title:             Grandview 9th Ward Elders Quorum Lessons
email:             rdviertel@gmail.com
description:       Lesson notes
author:            Grandview 9th Ward Elders Quorum
baseurl:           "/"
url:               "gv9eq.org"

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman
